version: '3.7'
services:
  sqldata:
      image: mcr.microsoft.com/mssql/server:2017-latest
      environment:
        - SA_PASSWORD=Pass@word
        - ACCEPT_EULA=Y
      ports:
        - "5434:1433"
      volumes:
        - sqlsystem:/var/opt/mssql/
        - sqldata:/var/opt/sqlserver/data
        - sqllog:/var/opt/sqlserver/log
        - sqlbackup:/var/opt/sqlserver/backup

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: